#!/bin/bash

set -e

for i in $(cat list)
do
  number=$(echo $i | cut -d"x" -f 1)
  rsvg-convert -a -w $(($number + 0)) -f 64x64/apps/pardus-store.svg -o "$i/apps/pardus-store.svg"
  rsvg-convert -a -w $(($number + 0)) -f 64x64/apps/pardus-imagewriter.svg -o "$i/apps/pardus-store.svg"
done
